language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .          # install root pynode
  - pip install ./pynode/. # install core submodule
# command to run tests
script:
  - python tests/launcher_test.py